import os
import pandas as pd

def generate_reports(df, reports_dir="reports"):
    """
    Creates HTML statistics tables and saves distribution charts to PNG format.
    Defensively imports matplotlib to support environments without UI headers.
    """
    print(f"[VIZ] Compiling summaries in destination folder: {reports_dir}")
    os.makedirs(reports_dir, exist_ok=True)
    
    # Render pandas description profile as HTML
    desc_table = df.describe(include='all').to_html(
        classes="w-full text-left font-mono border-collapse border border-slate-200 text-xs"
    )
    
    # Render dataset head preview as HTML
    preview_table = df.head(10).to_html(
        classes="w-full text-left font-mono border-collapse border border-slate-200 text-xs"
    )
    
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Pipeline Execution Telemetry</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        th, td {{ padding: 10px; border: 1px solid #e2e8f0; }}
        tr:nth-child(even) {{ background-color: #f8fafc; }}
    </style>
</head>
<body class="bg-slate-50 text-slate-800 p-8 font-sans">
    <div class="max-w-4xl mx-auto bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
        <h1 class="text-3xl font-bold text-slate-900 mb-2 border-b pb-4">Data Profiling Report</h1>
        <p class="text-[10px] text-slate-400 font-bold uppercase tracking-widest mb-8">Generated by ETL viz.py</p>
        
        <div class="grid grid-cols-2 gap-4 mb-8">
            <div class="bg-slate-50 p-5 rounded-xl border border-slate-100">
                <p class="text-xs uppercase font-bold text-slate-400 tracking-wider">Payload Rows</p>
                <p class="text-3xl font-bold mt-1 text-blue-600">{len(df)}</p>
            </div>
            <div class="bg-slate-50 p-5 rounded-xl border border-slate-100">
                <p class="text-xs uppercase font-bold text-slate-400 tracking-wider">Features Detected</p>
                <p class="text-3xl font-bold mt-1 text-slate-800">{len(df.columns)}</p>
            </div>
        </div>

        <h2 class="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4">Descriptive Analytics Table</h2>
        <div class="overflow-x-auto mb-8 border border-slate-200 rounded-xl">
            {desc_table}
        </div>

        <h2 class="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4">Ingress Data Preview (First 10 Rows)</h2>
        <div class="overflow-x-auto border border-slate-200 rounded-xl">
            {preview_table}
        </div>
    </div>
</body>
</html>
"""
    html_path = os.path.join(reports_dir, "report.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"[VIZ] Summary HTML page exported: {html_path}")

    # Generate matplotlib plot
    png_path = os.path.join(reports_dir, "chart.png")
    try:
        import matplotlib
        matplotlib.use('Agg') # Non-interactive backend
        import matplotlib.pyplot as plt
        
        plt.figure(figsize=(8, 4.5))
        numeric_cols = df.select_dtypes(include=['number']).columns
        if len(numeric_cols) > 0:
            metric_target = numeric_cols[0]
            df[metric_target].hist(bins=12, color='#3b82f6', edgecolor='#1d4ed8', grid=False)
            plt.title(f"Distribution: {metric_target}", fontsize=11, fontweight='bold')
            plt.xlabel(metric_target, fontsize=9)
            plt.ylabel("Frequency", fontsize=9)
        else:
            plt.text(0.5, 0.5, "No numeric variables found to plot.", ha='center', va='center')
            
        plt.tight_layout()
        plt.savefig(png_path, dpi=120)
        plt.close()
        print(f"[VIZ] Ingress chart plot generated: {png_path}")
    except Exception as e:
        print(f"[VIZ] Plotting exception: {e}. Writing standard placeholder chart...")
        with open(png_path, "w") as f:
            f.write("Active Pipeline Ingest Plot Placeholder (Matplotlib check failed)")
        print(f"[VIZ] Summary stub written: {png_path}")
