import os
import pandas as pd

def generate_reports(df, reports_dir="reports"):
    """
    Creates HTML summary statistics and saves visual charts as PNG.
    Uses matplotlib defensively with 'Agg' backend.
    """
    print(f"[VIZ] Compiling summaries in destination folder: {reports_dir}")
    os.makedirs(reports_dir, exist_ok=True)
    
    total_students = len(df)
    avg_marks = round(df["Final Marks"].mean(), 2)
    pass_count = len(df[df["Result"] == "Pass"])
    pass_pct = round((pass_count / total_students) * 100, 2)
    failed_count = total_students - pass_count
    
    # Calculate Department Distribution
    dept_counts = df["Department"].value_counts().to_dict()
    dept_marks = df.groupby("Department")["Final Marks"].mean().round(2).to_dict()
    
    # Render department performance summary table as HTML
    dept_summary_df = df.groupby("Department").agg(
        Total_Students=("StudentID", "count"),
        Average_Marks=("Final Marks", "mean"),
        Pass_Rate=("Result", lambda x: (sum(x == "Pass") / len(x)) * 100)
    ).round(2).reset_index()
    
    dept_table = dept_summary_df.to_html(
        classes="w-full text-left font-mono border-collapse border border-slate-200 text-xs",
        index=False
    )
    
    # Render top 10 students table as HTML
    top_10 = df.sort_values(by="Final Marks", ascending=False).head(10)[
        ["StudentID", "Name", "Department", "Final Marks", "Attendance", "Grade"]
    ]
    
    top_10_table = top_10.to_html(
        classes="w-full text-left font-mono border-collapse border border-slate-200 text-xs",
        index=False
    )
    
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Student Performance Analytics Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        th, td {{ padding: 10px; border: 1px solid #e2e8f0; }}
        tr:nth-child(even) {{ background-color: #f8fafc; }}
    </style>
</head>
<body class="bg-slate-50 text-slate-800 p-8 font-sans">
    <div class="max-w-4xl mx-auto bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
        <h1 class="text-3xl font-bold text-slate-900 mb-2 border-b pb-4">Student Performance Analytics Report</h1>
        <p class="text-[10px] text-slate-400 font-bold uppercase tracking-widest mb-8">Generated by EduAnalytics ETL viz.py</p>
        
        <div class="grid grid-cols-3 gap-4 mb-8">
            <div class="bg-slate-50 p-5 rounded-xl border border-slate-100">
                <p class="text-xs uppercase font-bold text-slate-400 tracking-wider">Total Students</p>
                <p class="text-3xl font-bold mt-1 text-blue-600">{total_students}</p>
            </div>
            <div class="bg-slate-50 p-5 rounded-xl border border-slate-100">
                <p class="text-xs uppercase font-bold text-slate-400 tracking-wider">Average Marks</p>
                <p class="text-3xl font-bold mt-1 text-slate-800">{avg_marks}%</p>
            </div>
            <div class="bg-slate-50 p-5 rounded-xl border border-slate-100">
                <p class="text-xs uppercase font-bold text-slate-400 tracking-wider">Pass Percentage</p>
                <p class="text-3xl font-bold mt-1 text-green-600">{pass_pct}%</p>
            </div>
        </div>

        <h2 class="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4">Department-wise Breakdown</h2>
        <div class="overflow-x-auto mb-8 border border-slate-200 rounded-xl">
            {dept_table}
        </div>

        <h2 class="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4">Top 10 Performers</h2>
        <div class="overflow-x-auto border border-slate-200 rounded-xl">
            {top_10_table}
        </div>
    </div>
</body>
</html>
"""
    html_path = os.path.join(reports_dir, "report.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"[VIZ] Summary HTML page exported: {html_path}")

    # Generate Matplotlib chart summary.png
    png_path = os.path.join(reports_dir, "summary.png")
    try:
        import matplotlib
        matplotlib.use('Agg') # Non-interactive backend
        import matplotlib.pyplot as plt
        
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
        
        # Subplot 1: Student Count by Department
        depts = list(dept_counts.keys())
        counts = list(dept_counts.values())
        ax1.bar(depts, counts, color='#3b82f6', edgecolor='#1d4ed8')
        ax1.set_title("Student Distribution by Department", fontsize=11, fontweight='bold')
        ax1.set_xlabel("Department", fontsize=9)
        ax1.set_ylabel("Number of Students", fontsize=9)
        
        # Subplot 2: Average Marks by Department
        avg_marks_list = [dept_marks.get(d, 0.0) for d in depts]
        ax2.bar(depts, avg_marks_list, color='#10b981', edgecolor='#047857')
        ax2.set_title("Average Marks by Department", fontsize=11, fontweight='bold')
        ax2.set_xlabel("Department", fontsize=9)
        ax2.set_ylabel("Average Marks (%)", fontsize=9)
        ax2.set_ylim(0, 100)
        
        plt.tight_layout()
        plt.savefig(png_path, dpi=120)
        plt.close()
        print(f"[VIZ] Ingress chart plot generated: {png_path}")
    except Exception as e:
        print(f"[VIZ] Plotting exception: {e}. Writing standard placeholder chart...")
        with open(png_path, "w") as f:
            f.write("Active Pipeline Ingest Plot Placeholder (Matplotlib check failed)")
        print(f"[VIZ] Summary stub written: {png_path}")
